export {
  array as ARR,
  either as E,
  eq as EQ,
  function as FN,
  io as IO,
  map as MAP,
  option as OP,
  optionT as OPT,
  ord as ORD,
  record as REC,
  set as SET,
  string as STR,
  taskEither as TE,
  taskOption as TO,
} from "fp-ts";
